### ISSUE TITLE
Title ve Description içinde arama / filtreleme

### ISSUE THREAD

**Issue by ramesaliyev** [hurriyet/api.hurriyet.com.tr#1]
Merhabalar, öncelikle elinize sağlık.

Title ve/veya Description gibi text alanları içinde arama / filtreleme yapmak örneğin articles ve benzeri endpointler için bir ihtiyaç gibi duruyor. Mesela içerik veya başlığında "bedelli askerlik" geçen haberleri getirebilmek güzel olurdu.

**Comment by ogun** [comment]
Merhaba,

API'nin gelişmesiyle birlikte /search/ enpoint'ini açacağız ve dediğiniz alanlar üzerinde arama imkanı olacak. http://www.hurriyet.com.tr/arama/ adresindeki sonuçları alabileceğiz.

İlginiz için teşekkürler.
