### ISSUE TITLE
Haber içeriğindeki resim bağlantıları sorunu.

### ISSUE THREAD

**Issue by nuriu** [hurriyet/api.hurriyet.com.tr#10]
Haber (Article) nesnesinin metin (Text) içeriğindeki resim bağlantıları sunucu tabanlı olduğu için (http://a.com/a.jpg yerine /a.jpg gibi) Electron tabanlı geliştirdiğim uygulamada aşağıdaki şekildeki gibi bir hata almaktayım. Benzer durumlar ile karşılaşanlar olabileceği için burada paylaşıyorum.

![Örnek Resim](http://i.hizliresim.com/88dVXa.png)

Metin içindeki resim etiketlerini el ile silerek içerikten kaldırmak istemediğim için resimleri gösterebilmek için uygun bir çözüm yöntemi arıyorum.

**Comment by ogun** [comment]
Sorun düzeltildi.
