### ISSUE TITLE
Id $filter'da kullanılamıyor

### ISSUE THREAD

**Issue by buremba** [hurriyet/api.hurriyet.com.tr#12]
Dökümanyasyonda Id $filter içinde kullanılabilir denilmiş ancak $filter parametresine Id eklendiğinde 500 hatası alıyoruz.

Eğer mümkünse CreatedDate gibi diğer attribute'leri de ekleyebilirseniz çok iyi olur. Şu anda yeni haberleri düzenli olarak alıp veri analizi yapmak istiyoruz ancak bu limitlerden olayı pek mümkün gözükmüyor.

**Comment by ogun** [comment]
Id'nin $filter içerisinde kullanılamama sorunu düzeltildi.
