### ISSUE TITLE
'Files' $select içinde çalışmıyor

### ISSUE THREAD

**Issue by buremba** [hurriyet/api.hurriyet.com.tr#13]
$select parametresine Id,Files değeri gönderdiğimde Files parametresi dolu olarak gelen haberler dahil olmak üzere hiçbir haberde Files döndürülmüyor.

**Comment by ogun** [comment]
sorun düzeltildi

**Comment by buremba** [comment]
Sanırım sorun devam ediyor. Gene aynı sorguyu çalıştırdığımda aynı cevabı alıyorum.

**Comment by ogun** [comment]
Merhaba, tekrar kontrol ediyorum

**Comment by ogun** [comment]
Files koleksiyonunu çekmek için $expand özelliğini de kullanmanız gerekiyor. İlgili sorgu aşağıdaki gibi olmalı, bu şekilde çalıştırdığımda düzgün sonuç alıyorum. Dökümanı da bu şekilde güncelleyeceğim.

Örnek sorgu:
https://api.hurriyet.com.tr/v1/articles?$select=Files&$expand=Files

**Comment by buremba** [comment]
Bilgilendirme için teşekkürler.
