### ISSUE TITLE
Filter'da Contains Çalışmıyor Mu?

### ISSUE THREAD

**Issue by aligoren** [hurriyet/api.hurriyet.com.tr#15]
contains içerisinde filter sorgusu yazarken  "An error has occurred." hatasını alıyorum.

API Explorer üzerinde gerçekleştiriyorum sorguyu. Ancak hata gelmekte. Bu benimle alakalı mı bilmediğim için kutucuklara girdiğim değerleri göstereyim.

filter = contains(Title, 'Istanbul');
select = Title,Description
top = 5

Hatalı bir sorgu mu yaptım acaba?

**Comment by aligoren** [comment]
.NET Kütüphanesini ekledim bu arada. Dilerseniz daha da güzel bir tasarım desenine göre özelleştirip örnek kütüphaneler arasında gösterebilirsiniz.

https://github.com/aligoren/HurriyetNet

**Comment by ogun** [comment]
Merhaba,

Şu anlık API üzerinde Title, Description ya da Text alanlarında contains ile arama mevcut değil. v1.1.0 ile gelecek /api/search/ hizmetiyle mümkün olacak.
