### ISSUE TITLE
$Filter Path ile Php de sonuç vermiyor

### ISSUE THREAD

**Issue by ogzcakar** [hurriyet/api.hurriyet.com.tr#16]
Dökümantasyona göre kullanım 
https://api.hurriyet.com.tr/v1/articles?%24filter=Path eq '/gundem/' 
bu şekilde olduğu yazıyor ayrıyeten Api Explorer içerisinde Path eq '/gundem/' filtrelemesinde sonuç veriyor fakat Php de sonuç gözükmüyor. Benim mi kullanımım hatalı acaba ?

**Comment by ogun** [comment]
Merhaba,

İstekte bulunduğunuz Url doğru görünüyor, eğer kodunuzun ilgili kısmını da paylaşabilirseniz kontrol edebiliriz.

**Comment by ogzcakar** [comment]
https://paste.ubuntu.com/23355120/ Buyrun @ogun Bey Api key kısmını bilerek sildim bir sorun olmasın diye

**Comment by fatihbuyuktas** [comment]
Merhaba,
Paylaştığınız kodu kendi API Key'imle ve Windows 10 üzerinde 64 bit Wampserver ile denedim. Sunucuya erişim hatası veriyor. Curl sunucuya hiç ulaşamıyor.
`cURL Error #:Failed to connect to api.hurriyet.com.tr port 443: Bad access`

PHP kodunu bir sunucu üzerine yerleştirdiğimde ise sorunsuz çalışıyor:
http://www.fatihbuyuktas.com/hurapitest.php

Acaba siz de lokal bir ortamda deniyor ve firewall/proxy nedeni ile erişemiyor olabilir misiniz?

**Comment by ogzcakar** [comment]
Merhabalar @fatihbuyuktas Bey
https://api.hurriyet.com.tr/v1/articles ile sorunsuz çalışıyor filtreleme yapınca çalışmıyor. Sizin localde curlda sorun var sanırsam 
Filtreleme kullanıldığın da yani https://api.hurriyet.com.tr/v1/articles?%24filter=Path eq '/gundem/' ile 
 Invalid argument supplied for foreach() in  hatası veriyor Api explorerda ki çıktıya bakılırsa filtreleme de json çıktısı veriyor ve bunu foreach ile çalışması gerek diye düşünüyorum ama hala sonuca ulaşamadım

**Comment by fatihbuyuktas** [comment]
json_decode null dönüyor öyle değil mi?

**Comment by ogzcakar** [comment]
Evet @fatihbuyuktas Bey echo veya print_r de de sonuç yok foreach da zaten direkt hata veriyor 
Garip ki sunucuda da aynı problem yaşıyorum fakat sizde aynı kodlar ile sunucuda çalışmış. Acaba api key kısıtlaması gibi birşey var mı

**Comment by fatihbuyuktas** [comment]
Hayır API Key kısıtlaması gibi bir şey yok.

Urlencode sorununuzu çözecektir.
Kodunuzu aşağıdaki şekilde değiştirip dener misiniz?

```
$query = urlencode("'%24filter=Path eq '/gundem/'");

curl_setopt_array($curl, array(
    CURLOPT_URL => "https://api.hurriyet.com.tr/v1/articles?".$query,
...
...
```

**Comment by ogzcakar** [comment]
Şimdi sonuç aldım @fatihbuyuktas Bey fakat aldığım sonuçlar içerisinde Spor , Spor/Futbol , Yerel-Haberler/Ankara/ gibi  ki zaten sizinde sunucuya attığınız halinde de (http://www.fatihbuyuktas.com/hurapitest.php) filtreleme pek mevcur değil yine bende olduğu gibi Spor gibi pathlarda mevcut

**Comment by fatihbuyuktas** [comment]
urlencode'u hatalı kullandığım için filter hiç çalışmamış.
Şu şekilde daha kolay yapalım:

`CURLOPT_URL => "https://api.hurriyet.com.tr/v1/articles?%24filter=Path%20eq%20%27%2Fgundem%2F%27",`

Sanıyorum bu şekilde gündem haberlerini doğru alırsınız.

**Comment by ogzcakar** [comment]
Teşekkür ederim @fatihbuyuktas Bey Çok uğraştırdım sizi ama sonuca doğru bir şekilde vardık tekrar teşekkürler :)

**Comment by ogzcakar** [comment]
Ayrıyeten Api Explorer Sayfasında Json çıktısının yanında yapılan sorgulamaya ait Url çıktısı da verse çok daha güzel olabilir

**Comment by fatihbuyuktas** [comment]
Rica ederiz.
Öneriniz için ayrıca teşekkürler.
