### ISSUE TITLE
İzinli Filtreler

### ISSUE THREAD

**Issue by enderahmetyurt** [hurriyet/api.hurriyet.com.tr#17]
Merhaba,

Bu repo üzerindeki README'de **$filter** örneği, 
`https://api.hurriyet.com.tr/v1/articles?$filter=Title eq 'Tatilde formda kalmak` şeklinde olmasına rağmen. [Offical dokümanlarda](https://developers.hurriyet.com.tr/docs/versions/1.0/resources/article/endpoints/list-articles) **$filter** alanı için _"OData sorgu filtresi bu alandan girilebilir. İzinli filtre property'leri: ModifiedDate, Path, Id"_ şeklinde yazılmış. Bu biraz yanıltıcı değil mi?

**Comment by ogun** [comment]
Merhaba,

Uyarınız için teşekkürler, dökümanı güncelledim.
