### ISSUE TITLE
`Article` `ModifiedDate` eksikliği

### ISSUE THREAD

**Issue by yigitozkavci** [hurriyet/api.hurriyet.com.tr#27]
`https://api.hurriyet.com.tr/v1/articles` burada her bir `article` için `ModifiedDate` alanı var fakat

`https://api.hurriyet.com.tr/v1/articles/40349649` burada yok.

**Comment by selcukusta** [comment]
@yigitozkavci selam, gerekli düzenlemeyi gerçekleştirdik. Sistem ekibimizin yayına çıkışı sonrasında ilgili field sonuçlara eklenecektir. Geri dönüş için teşekkürler.
