### ISSUE TITLE
Fikri mulkiyet haklari

### ISSUE THREAD

**Issue by NmC** [hurriyet/api.hurriyet.com.tr#3]
Merhabalar, sikca sorulan sorular kisminda

"HÜRRİYET" uygulamalarının, "Site"de yer alan bilgilerin ve "HÜRRİYET"in telif haklarına tabi çalışmalarının yeniden satışı, paylaşılması, dağıtılması, sergilenmesi ve üçüncü kişilerin erişimine sunulmasına "HÜRRİYET" tarafından izin verilmemektedir.

paragrafi yer almakta. Olayi tam olarak cozumleyemedim. Api vasitasiyla aldigimiz icerigi herhangi bir yerde yayinlayamiyor muyuz?

**Comment by ogun** [comment]
Merhaba,

İlgili bölüm aşağıdaki şekilde değiştirilmiştir. Uyarınız için teşekkürler.

"Üye"'nin sisteme kullanıcı adı ve parolasıyla giriş yapması neticesinde aktif hale gelen API anahtarı vasıtasıyla Site'de sunulan İçerikleri sadece işbu sözleşme kapsamında belirtilen amaç çerçevesinde, kendi tasarlayacağı formatta ya da orijinal haliyle yayınlayabilir veya sunabilir.
