### ISSUE TITLE
Api'den response alinmiyor

### ISSUE THREAD

**Issue by yavuzyurtbegendi** [hurriyet/api.hurriyet.com.tr#30]
`/pages` den response donmuyor.

**Comment by ogun** [comment]
Merhaba,

Sorunla ilgileniyoruz.

**Comment by yigitozkavci** [comment]
~~Merhaba, api'dan hem response alınmıyor hem de portal'dan api key alınamıyor. Genel bir problem mi var acaba?~~
**Edit:** Dünkü api key problemi çözülmüş gözüküyor.
@ogun

**Comment by ogun** [comment]
Merhaba,

Dün sistemdeki hata öğlen saatlerinde çözüldü ama buraya yazmayı atlamışım, kusura bakmayın. Uyarınız için teşekkürler.
