### ISSUE TITLE
post metodu kullanımı hk.

### ISSUE THREAD

**Issue by duygumiraloglu** [hurriyet/api.hurriyet.com.tr#31]
Merhaba, ben post metodunu kullanmak istiyorum. Apileriniz şu an sadece get metoduyla çalışıyor anladığım kadarıyla. Yakın zamanda post metodunu açmayı düşünüyor musunuz?

**Comment by ogun** [comment]
Merhaba,

POST kullanımını açmayı düşünmüyoruz. Nasıl bir sorun dolayısıyla POST metodu kullanmak istiyorsunuz belki bu sorunu çözebiliriz?

**Comment by duygumiraloglu** [comment]
api üzerinden ilan eklemek için ihtiyaç duydum.

**Comment by ogun** [comment]
Merhaba,

Şu anda API üzerinden içerik alımı yapmayı düşünmüyoruz. İlginiz için teşekkürler.
