### ISSUE TITLE
Hürriyet AMP sayfası

### ISSUE THREAD

**Issue by CagatayUNAL** [hurriyet/api.hurriyet.com.tr#32]
Merhaba,

Uzun zamandır Google AMP , AMP Project konusunu araştırıyorum.AMP sitenin,third-party yazılımları ve scriptleri kısıtladığını öğrendim ancak hurriyet.com.tr'ye baktığımda ve her haberinde mobil için amp sayfası olduğunu görünce çelişkiye düştüm. AMP static sayfa içinse hurriyet.com.tr nasıl amp oluyor sonuçta haberleri dynamic olarak oluşturuyor.Bu konuda bana yardım edebilir misiniz ?

**Comment by ogun** [comment]
Merhaba,

Hürriyet içerisindeki AMP sayfaları, var olan içeriğin istek anında AMP'ye uygun hale dönüştürülmesiyle oluşturuluyor.

Örneğin bir haber:
http://www.hurriyet.com.tr/iki-turk-muhendisi-gelistirdi-abd-ordusuna-sattilar-40433820

Aynı haberin AMP karşılığı:
http://www.hurriyet.com.tr/amp/iki-turk-muhendisi-gelistirdi-abd-ordusuna-sattilar-40433820
