### ISSUE TITLE
Angular 2 Client

### ISSUE THREAD

**Issue by akaramanapp** [hurriyet/api.hurriyet.com.tr#33]
Angular 2 client projesi oluşturarak ilgili api'lere direk request attığımda aşağıdaki hatayı alıyorum:

Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

Nasıl bir yol izlemeliyim ?

**Comment by ogun** [comment]
Merhaba,

Hürriyet Public API farklı bir domain'den hizmet verdiği için client-side bir uygulama ile bu API'den direkt sorgu çekemezsiniz. Bunun için bir ara katman yazıp, kendi domaininiz üzerinden çalışacak hale getirmeniz gerekiyor.
