### ISSUE TITLE
Github authentication problemi

### ISSUE THREAD

**Issue by ergunozyurt** [hurriyet/api.hurriyet.com.tr#4]
https://developers.hurriyet.com.tr/login ya da https://developers.hurriyet.com.tr/developers/new sayfalarındaki Github authentication çalışmıyor.

İlgili butona tıkladığımızda gelato.io sitesine herhangi bir uyarı ile karşılaşmadan yönleniyoruz. Yönlendiğimiz URL'den anlaşıldığı kadarıyla OAuth callback url hatalı konfigurasyonu söz konusu.

Yönlendirdiği url;

`https://gelato.io/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=7d7c2cf0b68820120b6834461fac43bf4fa659b23a035400`

API için tebrikler / teşekkürler.

**Comment by selcukusta** [comment]
Merhaba,

Geri bildiriminiz için teşekkürler. An itibariyle sorun çözülmüştür.
