### ISSUE TITLE
github login sorunu

### ISSUE THREAD

**Issue by sefaiyi** [hurriyet/api.hurriyet.com.tr#5]
github ile login kısmı çalışmıyor developer api sayfasına kayıt ol kısmında, twitter ile kayıt oldum bir sıkıntı yok o kısımda.

**Comment by nuriu** [comment]
#4 ile bahsedilen sorun sanırım.

**Comment by selcukusta** [comment]
Merhaba,

#4 numaralı issue'da da belirtildiği üzere sorun çözülmüştür. Geri bildiriminiz için teşekkür ediyoruz.
