### ISSUE TITLE
Stream Haberler

### ISSUE THREAD

**Issue by mertingen** [hurriyet/api.hurriyet.com.tr#6]
İyi günler, haberleri stream edeceğimiz bir yapı olacak mı, yeni bir haber postu geldiğinde eventi'i yakabilecek miyiz yani?

**Comment by selcukusta** [comment]
Merhaba,

Şu anda bu tür bir yapı API tarafında yer almamaktadır. Ek geliştirme planına dahil edilip edilmeyeceği konusunda değerlendirilmek üzere listeye alınmıştır.

Geri bildiriminiz için de teşekkür ediyoruz.
